# Generated by Django 4.1.7 on 2023-04-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loai',
            fields=[
                ('maloai', models.AutoField(primary_key=True, serialize=False)),
                ('tenloai', models.CharField(default='Chưa phân loại', max_length=45, unique=True)),
                ('mota', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
